In [1]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("accidents")

Connected to project 'accidents'.

# Task: Accidents
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *Accidents* dataset is a comprehensive collection of traffic accident data from Ljubljana, Slovenia, covering the years 1995 to 2005. It is used primarily for multiclass classification tasks to analyze and predict accident characteristics.
> 
> **Data Model:**
> - The dataset is organized into three main tables: `oseba`, `nesreca`, and `upravna_enota`.
> - Key attributes include `id_nesreca`, `klas_nesreca`, `cas_nesreca`, and various demographic and accident-related details.
> 
> **Task and Target Column:**
> - The primary task is *multiclass classification*, focusing on predicting the class of the accident.
> - The target column is `klas_nesreca` in the `nesreca` table.
> 
> **Column Types:**
> - The dataset includes a variety of data types:
>   - *Char* (e.g., `id_nesreca`, `spol`)
>   - *Tinyint* (e.g., `starost`)
>   - *Decimal* (e.g., `alkotest`)
>   - *Datetime* (e.g., `cas_nesreca`)
>   - *Int* and *Double* for coordinates and other numeric data
> 
> **Metadata:**
> - Size: 234.5 MB
> - Number of tables: 3
> - Total number of rows: 1,453,650
> - Total number of columns: 43
> - Missing values: Yes
> - Target table: `nesreca`
> - Target ID: `id_nesreca`
> - Target timestamp: `cas_nesreca`
> 
> **Research and Usage:**
> - The dataset is utilized in government and public safety research to improve traffic safety measures.
> - It provides insights into accident patterns and helps in developing predictive models for traffic management.
> 
> This dataset is a valuable resource for analyzing traffic accidents and developing strategies to enhance road safety.

### Tables
Population table: nesreca

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/Accidents.svg" alt="Accidents ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
nesreca, peripheral = load_ctu_dataset("Accidents")

(
    oseba,
    upravna_enota,
) = peripheral.values()

Analyzing schema:   0%|          | 0/3 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/3 [00:00<?, ?it/s]

Building data:   0%|          | 0/3 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`nesreca`).

We already set the `target` role for the target (`klas_nesreca`).

In [3]:
# TODO: Annotate remaining columns with roles
nesreca

  name              x              y        x_wgs84        y_wgs84   ...   vreme_nesreca   stanje_promet   stanje_vozisce
  role   unused_float   unused_float   unused_float   unused_float   ...   unused_string   unused_string   unused_string
     0         556102         159758        15.7271        46.5795   ...   O               R               MO
     1         423380          95390        14.006         45.9984   ...   J               N               MO
     2         555372         150260        15.7165        46.4941   ...   O               R               MO
     3         425085          96093        14.0279        46.0049   ...   J               N               PN
     4         460758         100064        14.4882        46.0436   ...   O               R               SP
                  ...            ...        ...            ...             ...             ...             ...
508988         395782          44457        13.6608        45.5366   ...   J               R               SU
508989         399890          44778        13.7134        45.54     ...   J               N               SU
508990         397155          44707        13.6784        45.539    ...   O               N               MO
508991         395841          44524        13.6616        45.5372   ...   O               N               SU
508992         393977          43662        13.6379        45.5291   ...   O               N               MO

  name   stanje_povrsina_vozisce   split
  role   unused_string             unused_string
     0   A                         train
     1   A                         train
     2   A                         train
     3   A                         train
     4   A                         val
         ...                       ...
508988   A                         val
508989   A                         val
508990   A                         train
508991   A                         val
508992   A                         train


508993 rows x 23 columns
memory usage: 151.50 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
oseba

  name        starost   vozniski_staz_LL   vozniski_staz_MM       alkotest   ...   varnostni_pas_ali_celada   starost_d
  role   unused_float       unused_float       unused_float   unused_float   ...   unused_string              unused_string
     0             38                 6                nan            0.11   ...   N                          D
     1             28                10                nan            0      ...   N                          C
     2             12                 0                nan          nan      ...   0                          B
     3             24                 6                nan          nan      ...   D                          C
     4             27                 6                nan          nan      ...   D                          C
                  ...                ...                ...          ...           ...                        ...
954031             18               nan                nan            0      ...   1                          B
954032             27                 8                  9            0      ...   1                          C
954033             25                 6                 10            0      ...   1                          C
954034             41                 4                  1            0.96   ...   1                          E
954035             24                 0                 10            0      ...   1                          C

  name   vozniski_staz_d   alkotest_d      strokovni_pregled_d
  role   unused_string     unused_string   unused_string
     0   B                 B               B
     1   B                 A               A
     2   A                 N               N
     3   B                 N               N
     4   B                 N               N
         ...               ...             ...
954031   N                 A               A
954032   B                 A               A
954033   B                 A               A
954034   A                 C               A
954035   A                 A               A


954036 rows x 17 columns
memory usage: 163.11 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
upravna_enota

name   st_prebivalcev       povrsina   id_upravna_enota   ime_upravna_enota
role     unused_float   unused_float   unused_string      unused_string
   0            23507            353   5501               Ajdovščina
   1            23253            268   5502               Brežice
   2            62049            230   5503               Celje
   3            16155            483   5504               Cerknica
   4            18290            486   5505               Črnomelj
                  ...            ...   ...                ...
  59           145678            356   5564               Maribor
  60            19750            171   5565               Pesnica
  61            15054            209   5568               Ruše
  62                0              0   5598               MNZ
  63                0              0   5599               Neznana


64 rows x 4 columns
memory usage: 0.00 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/Accidents](https://relational.fel.cvut.cz/dataset/Accidents)
for a description of the dataset.

In [6]:
dm = getml.data.DataModel(population=nesreca.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [7]:
container = getml.data.Container(population=nesreca, split=nesreca.split)
container.add(**peripheral)

container

population
    subset   name        rows   type
0   train    nesreca   356296   View
1   val      nesreca   152697   View

peripheral
    name              rows   type
0   oseba           954036   DataFrame
1   upravna_enota       64   DataFrame