In [1]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("db_transformer_imdb_ijs")

Connected to project 'db_transformer_imdb_ijs'.

# Task: imdb_ijs
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *imdb_ijs* dataset is a relational database designed to capture information about movies, directors, actors, and genres. Below is a description based on the provided schema:
> 
> - *Data Model (Relational Schema)*:
>   - **directors_genres**: Links directors to genres with a probability score.
>     - Columns: `director_id` (int), `genre` (varchar), `prob` (float)
>   - **movies_directors**: Associates directors with movies.
>     - Columns: `director_id` (int), `movie_id` (int)
>   - **movies_genres**: Associates movies with genres.
>     - Columns: `movie_id` (int), `genre` (varchar)
>   - **roles**: Details the roles actors play in movies.
>     - Columns: `actor_id` (int), `movie_id` (int), `role` (varchar)
>   - **directors**: Contains information about directors.
>     - Columns: `id` (int), `first_name` (varchar), `last_name` (varchar)
>   - **movies**: Contains information about movies.
>     - Columns: `id` (int), `name` (varchar), `year` (int), `rank` (float)
>   - **actors**: Contains information about actors.
>     - Columns: `id` (int), `first_name` (varchar), `last_name` (varchar), `gender` (char)
> 
> - *Task*: The dataset can be used for various tasks such as classification (e.g., predicting movie genres based on directors and actors) or regression (e.g., predicting movie rank).
> 
> - *Target Column*: Depending on the task, target columns could be `genre` for classification or `rank` for regression.
> 
> - *Column Types*: The dataset includes integer, varchar, float, and char data types.
> 
> - *Metadata*:
>   - Size: Not specified
>   - Number of Tables: 7
>   - Number of Rows: Not specified
> 
> This dataset provides a comprehensive view of the relationships between movies, directors, actors, and genres, making it suitable for various analytical tasks.

### Tables
Population table: actors

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/imdb_ijs.svg" alt="imdb_ijs ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
actors, peripheral = load_ctu_dataset("imdb_ijs")

(
    directors,
    movies_directors,
    roles,
    movies_genres,
    movies,
    directors_genres,
) = peripheral.values()

Analyzing schema:   0%|          | 0/7 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/7 [00:00<?, ?it/s]

Building data:   0%|          | 0/7 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`actors`). We already set the `target` role for the target (`gender`). If the task is a multiclass classification,
we split the target column into multiple columns in an one-vs-all fashion. In this case, the original target is still avaiable as `gender`.

In [3]:
# TODO: Annotate remaining columns with roles
actors

  name   gender   id              first_name      last_name            split
  role   target   unused_string   unused_string   unused_string        unused_string
     0        0   2               Michael         'babeepower' Viera   train
     1        0   3               Eloy            'Chincheta'          train
     2        0   4               Dieguito        'El Cigala'          val
     3        0   5               Antonio         'El de Chipiona'     train
     4        0   6               José            'El Francés'         val
            ...   ...             ...             ...                  ...
817713        1   845461          Herdís          Þorvaldsdóttir       train
817714        1   845462          Katla Margrét   Þorvaldsdóttir       val
817715        1   845463          Lilja Nótt      Þórarinsdóttir       val
817716        1   845464          Hólmfríður      Þórhallsdóttir       train
817717        1   845465          Theódóra        Þórðardóttir         val


817718 rows x 5 columns
memory usage: 55.16 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
directors

  name   director_id     genre           prob
  role   unused_string   unused_string   unused_string
     0   2               Short           1
     1   3               Drama           1
     2   5               Documentary     1
     3   6               Drama           1
     4   6               Short           1
         ...             ...             ...
156557   88797           Drama           1
156558   88798           Adventure       1
156559   88799           Short           1
156560   88800           Animation       1
156561   88800           Comedy          1


156562 rows x 3 columns
memory usage: 6.59 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
movies_directors

  name   movie_id        genre
  role   unused_string   unused_string
     0   1               Documentary
     1   1               Short
     2   2               Comedy
     3   2               Crime
     4   5               Western
         ...             ...
395114   378612          Adventure
395115   378612          Drama
395116   378613          Comedy
395117   378613          Drama
395118   378614          Comedy


395119 rows x 2 columns
memory usage: 11.89 MB
type: getml.DataFrame

In [6]:
# TODO: Annotate columns with roles
roles

   name   actor_id        movie_id        role
   role   unused_string   unused_string   unused_string
      0   2               280088          Stevie
      1   2               396232          Various/lyricist
      2   3               376687          Gitano 1
      3   4               336265          El Cigala
      4   5               135644          Himself
          ...             ...             ...
3431961   845461          137097          Kata
3431962   845462          208838          Magga
3431963   845463          870             Gunna
3431964   845464          378123          Gudrun
3431965   845465          378123          NULL


3431966 rows x 3 columns
memory usage: 162.07 MB
type: getml.DataFrame

In [7]:
# TODO: Annotate columns with roles
movies_genres

  name   director_id     movie_id
  role   unused_string   unused_string
     0   1               378879
     1   2               281325
     2   3               30621
     3   3               304743
     4   4               60570
         ...             ...
371175   88797           172648
371176   88798           350996
371177   88799           189713
371178   88800           105513
371179   88801           97098


371180 rows x 2 columns
memory usage: 10.63 MB
type: getml.DataFrame

In [8]:
# TODO: Annotate columns with roles
movies

  name   id              name                               year            rank
  role   unused_string   unused_string                      unused_string   unused_string
     0   0               #28                                2002            NULL
     1   1               #7 Train: An Immigrant Journey, ...   2000            NULL
     2   2               $                                  1971            6.4
     3   3               $1,000 Reward                      1913            NULL
     4   4               $1,000 Reward                      1915            NULL
         ...             ...                                ...             ...
388264   412316          "zem blch krlu"                    1991            NULL
388265   412317          "rgammk"                           1995            NULL
388266   412318          "zgnm Leyla"                       2002            NULL
388267   412319          " Istanbul"                        1983            NULL
388268   412320          "sterreich"                        1958            NULL


388269 rows x 4 columns
memory usage: 25.05 MB
type: getml.DataFrame

In [9]:
# TODO: Annotate columns with roles
directors_genres

 name   id              first_name      last_name
 role   unused_string   unused_string   unused_string
    0   1               Todd            1
    1   2               Les             12 Poissons
    2   3               Lejaren         a'Hiller
    3   4               Nian            A
    4   5               Khairiya        A-Mansour
        ...             ...             ...
86875   88797           Yusuf           Ünal
86876   88798           Ahmet           Ündag
86877   88799           Idil            Üner
86878   88800           Yüksel          Ünsal
86879   88801           Ahmet           Üstel


86880 rows x 3 columns
memory usage: 3.94 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/imdb_ijs](https://relational.fel.cvut.cz/dataset/imdb_ijs)
for a description of the dataset.

In [10]:
dm = getml.data.DataModel(population=actors.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [11]:
container = getml.data.Container(population=actors, split=actors.split)
container.add(**peripheral)

container

population
    subset   name       rows   type
0   train    actors   572403   View
1   val      actors   245315   View

peripheral
    name                  rows   type
0   directors_genres    156562   DataFrame
1   movies_genres       395119   DataFrame
2   roles              3431966   DataFrame
3   movies_directors    371180   DataFrame
4   movies              388269   DataFrame
5   directors            86880   DataFrame