In [1]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("pima")

Connected to project 'pima'.

# Task: Pima
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *Pima* dataset is a well-known dataset used for medical research, specifically focusing on diabetes prediction among Pima Indian women. It originates from a study conducted by the National Institute of Diabetes and Digestive and Kidney Diseases.
> 
> **Data Model:**
> - The dataset is organized into multiple tables: `age`, `bmi`, `diastolic`, `numPreg`, `pedigree`, `plasma`, `serum`, `tricepts`, and `pima`.
> - Each table contains two columns: `arg1` (varchar) and `arg2` (decimal for most tables, varchar for `pima`).
> 
> **Task and Target Column:**
> - The primary task is *classification*, aiming to predict the presence of diabetes.
> - The target column is `arg2` in the `pima` table.
> 
> **Column Types:**
> - The dataset includes:
>   - *Varchar* (e.g., `arg1`)
>   - *Decimal* (e.g., `arg2` in most tables)
> 
> **Metadata:**
> - Size: 700 KB
> - Number of tables: 9
> - Total number of rows: 6,912
> - Total number of columns: 18
> - Missing values: No
> - Target table: `pima`
> - Target ID: `arg1`
> 
> **Research and Usage:**
> - The dataset is widely used in medical research for developing models to predict diabetes.
> - It is a popular choice for testing classification algorithms due to its real-world medical data.
> 
> This dataset provides a valuable resource for exploring medical data analysis, particularly in predicting diabetes based on various health indicators.

### Tables
Population table: pima

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/Pima.svg" alt="Pima ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
pima, peripheral = load_ctu_dataset("Pima")

(
    age,
    bmi,
    diastolic,
    numPreg,
    pedigree,
    plasma,
    serum,
    tricepts,
) = peripheral.values()

Analyzing schema:   0%|          | 0/9 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/9 [00:00<?, ?it/s]

Building data:   0%|          | 0/9 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`pima`).

We already set the `target` role for the target (`arg2`).


arg2 is the target column for a binary classification task.

In [3]:
# TODO: Annotate remaining columns with roles
pima

name     arg2   arg1            split
role   target   unused_string   unused_string
   0        0   A1              train
   1        0   A10             train
   2        0   A100            val
   3        0   A101            train
   4        1   A102            train
          ...   ...             ...
 763        1   A95             train
 764        1   A96             train
 765        1   A97             val
 766        1   A98             val
 767        1   A99             train


768 rows x 3 columns
memory usage: 0.03 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
age

name           arg2   arg1
role   unused_float   unused_string
   0             50   A1
   1             54   A10
   2             31   A100
   3             33   A101
   4             22   A102
                ...   ...
 763             21   A95
 764             40   A96
 765             24   A97
 766             22   A98
 767             23   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
bmi

name           arg2   arg1
role   unused_float   unused_string
   0           33.6   A1
   1            0     A10
   2           49.7   A100
   3           39     A101
   4           26.1   A102
               ...    ...
 763           24.7   A95
 764           33.9   A96
 765           31.6   A97
 766           20.4   A98
 767           28.7   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [6]:
# TODO: Annotate columns with roles
diastolic

name           arg2   arg1
role   unused_float   unused_string
   0             72   A1
   1             96   A10
   2             90   A100
   3             72   A101
   4             60   A102
                ...   ...
 763             82   A95
 764             72   A96
 765             62   A97
 766             48   A98
 767             50   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [7]:
# TODO: Annotate columns with roles
numPreg

name           arg2   arg1
role   unused_float   unused_string
   0              6   A1
   1              8   A10
   2              1   A100
   3              1   A101
   4              1   A102
                ...   ...
 763              2   A95
 764              6   A96
 765              2   A97
 766              1   A98
 767              6   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [8]:
# TODO: Annotate columns with roles
pedigree

name           arg2   arg1
role   unused_float   unused_string
   0          0.627   A1
   1          0.232   A10
   2          0.325   A100
   3          1.222   A101
   4          0.179   A102
             ...      ...
 763          0.761   A95
 764          0.255   A96
 765          0.13    A97
 766          0.323   A98
 767          0.356   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [9]:
# TODO: Annotate columns with roles
plasma

name           arg2   arg1
role   unused_float   unused_string
   0            148   A1
   1            125   A10
   2            122   A100
   3            163   A101
   4            151   A102
                ...   ...
 763            142   A95
 764            144   A96
 765             92   A97
 766             71   A98
 767             93   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [10]:
# TODO: Annotate columns with roles
serum

name           arg2   arg1
role   unused_float   unused_string
   0              0   A1
   1              0   A10
   2            220   A100
   3              0   A101
   4              0   A102
                ...   ...
 763             64   A95
 764            228   A96
 765              0   A97
 766             76   A98
 767             64   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

In [11]:
# TODO: Annotate columns with roles
tricepts

name           arg2   arg1
role   unused_float   unused_string
   0             35   A1
   1              0   A10
   2             51   A100
   3              0   A101
   4              0   A102
                ...   ...
 763             18   A95
 764             27   A96
 765             28   A97
 766             18   A98
 767             30   A99


768 rows x 2 columns
memory usage: 0.02 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/Pima](https://relational.fel.cvut.cz/dataset/Pima)
for a description of the dataset.

In [12]:
dm = getml.data.DataModel(population=pima.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [13]:
container = getml.data.Container(population=pima, split=pima.split)
container.add(**peripheral)

container

population
    subset   name   rows   type
0   train    pima    538   View
1   val      pima    230   View

peripheral
    name        rows   type
0   age          768   DataFrame
1   bmi          768   DataFrame
2   diastolic    768   DataFrame
3   num_preg     768   DataFrame
4   pedigree     768   DataFrame
5   plasma       768   DataFrame
6   serum        768   DataFrame
7   tricepts     768   DataFrame