In [1]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("sales_db")

Connected to project 'sales_db'.

# Task: SalesDB
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *SalesDB* dataset is a synthetic database structured in a star schema, designed to simulate sales transactions. The task is a *regression* task, with the target column being `Quantity` in the `Sales` table, representing the quantity of products sold.
> 
> **Data Model:**
> - **Tables:** 4 (Sales, Employees, Customers, Products)
> - **Columns:**
>   - **Sales:** Details of sales transactions, including the target column `Quantity`.
>   - **Employees:** Information about sales personnel.
>   - **Customers:** Customer details.
>   - **Products:** Product information, including price.
> 
> **Task and Target:**
> - **Task:** Regression
> - **Target Column:** `Quantity` (in the Sales table)
> 
> **Metadata:**
> - **Size:** 584.3 MB
> - **Number of Rows:** 6,718,978
> - **Number of Columns:** 16
> - **Missing Values:** Yes
> - **Compound Keys:** No
> - **Loops:** No
> - **Type:** Synthetic
> - **Instance Count:** 6,698,788
> 
> This dataset is used to analyze sales patterns and performance, providing insights into retail operations and customer behavior.

### Tables
Population table: sales

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/SalesDB.svg" alt="SalesDB ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
sales, peripheral = load_ctu_dataset("SalesDB")

(
    customers,
    employees,
    products,
) = peripheral.values()

Analyzing schema:   0%|          | 0/4 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/4 [00:00<?, ?it/s]

Building data:   0%|          | 0/4 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`sales`).

We already set the `target` role for the target (`Quantity`).


Quantity is the target column for a regression task.

In [3]:
# TODO: Annotate remaining columns with roles
sales

   name   Quantity        SalesID   SalesPersonID     CustomerID      ProductID   split
   role     target   unused_float    unused_float   unused_float   unused_float   unused_string
      0        500              1              17          10482            500   train
      1        810              2               5           1964            306   train
      2        123              3               8          12300            123   train
      3        437              4               1           4182            437   val
      4        750              5              14          15723            246   val
               ...            ...             ...            ...            ...   ...
6715216         59        6737973              11          16960             59   train
6715217         59        6737974              11          16960             59   train
6715218         59        6737975              11          16960             59   train
6715219         59        6737976              11          16960             59   train
6715220         59        6737977              11          16960             59   train


6715221 rows x 6 columns
memory usage: 358.59 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
customers

 name     CustomerID   FirstName       MiddleInitial   LastName
 role   unused_float   unused_string   unused_string   unused_string
    0              1   Aaron           NULL            Alexander
    1              2   Aaron           NULL            Bryant
    2              3   Aaron           NULL            Butler
    3              4   Aaron           NULL            Chen
    4              5   Aaron           NULL            Coleman
                 ...   ...             ...             ...
19754          19755   Zoe             L               Sanders
19755          19756   Zoe             R               James
19756          19757   Zoe             R               Ramirez
19757          19758   Zoe             S               Sanchez
19758          19759   Zoe             W               Watson


19759 rows x 4 columns
memory usage: 0.93 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
employees

name     EmployeeID   FirstName       MiddleInitial   LastName
role   unused_float   unused_string   unused_string   unused_string
   0              1   Abraham         e               Bennet
   1              2   Reginald        l               Blotchet-Halls
   2              3   Cheryl          a               Carson
   3              4   Michel          e               DeFrance
   4              5   Innes           e               del Castillo
                ...   ...             ...             ...
  18             19   Meander         m               Smith
  19             20   Dean            t               Straight
  20             21   Dirk            t               Stringer
  21             22   Johnson         h               White
  22             23   Akiko           o               Yokomoto


23 rows x 4 columns
memory usage: 0.00 MB
type: getml.DataFrame

In [6]:
# TODO: Annotate columns with roles
products

name      ProductID          Price   Name
role   unused_float   unused_float   unused_string
   0              1           1.6    Adjustable Race
   1              2           0.8    Bearing Ball
   2              3           2.4    BB Ball Bearing
   3              4           0      Headset Ball Bearings
   4              5         189.6    Blade
                ...          ...     ...
 499            500         101.24   ML Bottom Bracket
 500            501         121.49   HL Bottom Bracket
 501            502         539.99   Road-750 Black, 44
 502            503         539.99   Road-750 Black, 48
 503            504         539.99   Road-750 Black, 52


504 rows x 3 columns
memory usage: 0.02 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/SalesDB](https://relational.fel.cvut.cz/dataset/SalesDB)
for a description of the dataset.

In [7]:
dm = getml.data.DataModel(population=sales.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [8]:
container = getml.data.Container(population=sales, split=sales.split)
container.add(**peripheral)

container

population
    subset   name       rows   type
0   train    sales   4700655   View
1   val      sales   2014566   View

peripheral
    alias       name         rows   type
0   customers   Customers   19759   DataFrame
1   employees   Employees      23   DataFrame
2   products    Products      504   DataFrame