In [1]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("db_transformer_voc")

Connected to project 'db_transformer_voc'.

# Task: voc
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *VOC* dataset provides insights into the administrative system of the Vereenigde geoctrooieerde Oostindische Compagnie (VOC), also known as the Dutch East India Company, established in 1602.
> 
> - **Data Model:**
>   - *craftsmen, impotenten, passengers, seafarers, soldiers, total* tables:
>     - `number` (int): Identifier for the record.
>     - `number_sup` (char): Supplementary identifier.
>     - `trip` (int): Trip identifier.
>     - `trip_sup` (char): Supplementary trip identifier.
>     - Various columns for onboard, death, and left counts at different stages (int).
>   - *invoices* table:
>     - `number` (int): Invoice number.
>     - `number_sup` (char): Supplementary number.
>     - `invoice` (int): Invoice identifier.
>     - `chamber` (char): Chamber identifier.
>   - *voyages* table:
>     - `artificial_id` (char): Artificial identifier.
>     - `number` (int): Voyage number.
>     - `number_sup` (char): Supplementary number.
>     - `trip` (int): Trip identifier.
>     - `trip_sup` (char): Supplementary trip identifier.
>     - Various columns for ship details, dates, and harbors (varchar, int, date, text).
> 
> - **Task:**
>   - The primary task is *classification*, with the target column being `arrival_harbour` in the *voyages* table.
> 
> - **Column Types:**
>   - Integer (`int`) for identifiers and counts.
>   - Character (`char`) for supplementary identifiers.
>   - Variable character (`varchar`) for names and types.
>   - Date (`date`) for temporal data.
>   - Text (`text`) for particulars.
> 
> - **Metadata:**
>   - The dataset is real and contains missing values.
>   - It consists of 8 tables with a total of 29,067 rows and 89 columns.
>   - The dataset size is approximately 2.7 MB.
>   - There are 8,073 instances, with the target table being *voyages*.
> 
> This dataset is valuable for historical and retail analysis, focusing on the operations and logistics of a major historical trading company.

### Tables
Population table: voyages

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/voc.svg" alt="voc ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
voyages, peripheral = load_ctu_dataset("voc")

(
    soldiers,
    total,
    impotenten,
    seafarers,
    invoices,
    craftsmen,
    passengers,
) = peripheral.values()

Analyzing schema:   0%|          | 0/8 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/8 [00:00<?, ?it/s]

Building data:   0%|          | 0/8 [00:00<?, ?it/s]

You are splitting the column into more than 10 target columns. This might take a long time to fit.

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`voyages`). We already set the `target` role for the target (`arrival_harbour`). If the task is a multiclass classification,
we split the target column into multiple columns in an one-vs-all fashion. In this case, the original target is still avaiable as `arrival_harbour`.

In [3]:
# TODO: Annotate remaining columns with roles
voyages

name   arrival_harbour=-1   arrival_harbour=0   arrival_harbour=1   arrival_harbour=10   ...   cape_call       arrival_date
role               target              target              target               target   ...   unused_string   unused_string
   0                    0                   1                   0                    0   ...   t               1596-06-06
   1                    0                   1                   0                    0   ...   t               1596-06-06
   2                    0                   1                   0                    0   ...   t               1596-06-06
   3                    0                   1                   0                    0   ...   t               1596-06-06
   4                    0                   0                   1                    0   ...   t               1599-03-01
                      ...                 ...                 ...                  ...         ...             ...
8126                    0                   0                   0                    0   ...   t               1795-09-18
8127                    1                   0                   0                    0   ...   t               NULL
8128                    1                   0                   0                    0   ...   t               NULL
8129                    1                   0                   0                    0   ...   t               NULL
8130                    1                   0                   0                    0   ...   t               NULL

name   next_voyage     particulars                        split
role   unused_string   unused_string                      unused_string
   0   NULL            from 04-08 till 11-08 in the Mos...   train
   1   5001            HOLLANDIA on 26-10-1595; he was ...   val
   2   5002            Jan Dignumsz. died on 29-05-1595...   val
   3   5003            Jan Jansz. died on 25-12-1596 an...   train
   4   5010            other.                             train
       ...             ...                                ...
8126   4772            NULL                               train
8127   4674            to return because of adverse win...   train
8128   4774            Almost all data concerning this ...   train
8129   4777            Almost all data concerning this ...   val
8130   4778            the English at the Cape.           val


8131 rows x 86 columns
memory usage: 6.96 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
soldiers

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   1376            NULL            3               NULL            ...   NULL            NULL            NULL
   1   1378            NULL            5               NULL            ...   NULL            NULL            NULL
   2   1379            NULL            5               NULL            ...   NULL            NULL            NULL
   3   1380            NULL            3               NULL            ...   NULL            NULL            NULL
   4   1381            NULL            5               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
2344   8294            NULL            1               NULL            ...   NULL            NULL            NULL
2345   8320            NULL            2               NULL            ...   NULL            NULL            NULL
2346   8326            NULL            1               NULL            ...   NULL            NULL            NULL
2347   8329            NULL            2               NULL            ...   NULL            NULL            NULL
2348   8341            NULL            2               NULL            ...   NULL            NULL            NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   NULL                  19
   1   NULL                  22
   2   2                     16
   3   1                     10
   4   NULL                  11
       ...                   ...
2344   NULL                  NULL
2345   NULL                  NULL
2346   NULL                  NULL
2347   NULL                  NULL
2348   NULL                  NULL


2349 rows x 10 columns
memory usage: 0.23 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
total

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   310             NULL            2               NULL            ...   NULL            NULL            NULL
   1   311             NULL            2               NULL            ...   NULL            NULL            NULL
   2   318             NULL            5               NULL            ...   NULL            NULL            NULL
   3   320             NULL            3               NULL            ...   NULL            NULL            NULL
   4   321             NULL            2               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
2808   8354            NULL            2               NULL            ...   NULL            NULL            NULL
2809   8371            NULL            3               NULL            ...   NULL            NULL            NULL
2810   8384            NULL            1               NULL            ...   NULL            NULL            NULL
2811   8390            NULL            3               NULL            ...   1               7               NULL
2812   8396            NULL            3               NULL            ...   NULL            NULL            NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   2                     64
   1   5                     55
   2   4                     13
   3   NULL                  NULL
   4   NULL                  NULL
       ...                   ...
2808   NULL                  NULL
2809   NULL                  NULL
2810   NULL                  NULL
2811   NULL                  NULL
2812   NULL                  NULL


2813 rows x 10 columns
memory usage: 0.27 MB
type: getml.DataFrame

In [6]:
# TODO: Annotate columns with roles
impotenten

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   196             NULL            1               NULL            ...   NULL            NULL            NULL
   1   197             NULL            1               NULL            ...   NULL            NULL            NULL
   2   296             NULL            1               NULL            ...   NULL            NULL            NULL
   3   298             NULL            1               NULL            ...   NULL            NULL            NULL
   4   299             NULL            1               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
4463   8351            NULL            2               NULL            ...   22              20              NULL
4464   8354            NULL            2               NULL            ...   13              19              NULL
4465   8371            NULL            3               NULL            ...   NULL            NULL            NULL
4466   8384            NULL            1               NULL            ...   NULL            NULL            NULL
4467   8396            NULL            3               NULL            ...   1               11              NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   NULL                  NULL
   1   NULL                  NULL
   2   NULL                  NULL
   3   NULL                  NULL
   4   NULL                  NULL
       ...                   ...
4463   NULL                  NULL
4464   NULL                  NULL
4465   NULL                  NULL
4466   NULL                  NULL
4467   NULL                  NULL


4468 rows x 10 columns
memory usage: 0.46 MB
type: getml.DataFrame

In [7]:
# TODO: Annotate columns with roles
seafarers

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   296             NULL            1               NULL            ...   NULL            NULL            NULL
   1   298             NULL            1               NULL            ...   NULL            NULL            NULL
   2   299             NULL            1               NULL            ...   NULL            NULL            NULL
   3   300             NULL            1               NULL            ...   NULL            NULL            NULL
   4   301             NULL            1               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
4172   8348            NULL            2               NULL            ...   NULL            NULL            NULL
4173   8350            NULL            1               NULL            ...   NULL            NULL            NULL
4174   8351            NULL            2               NULL            ...   NULL            NULL            NULL
4175   8354            NULL            2               NULL            ...   NULL            NULL            NULL
4176   8396            NULL            3               NULL            ...   NULL            NULL            NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   NULL                  NULL
   1   NULL                  NULL
   2   NULL                  NULL
   3   NULL                  NULL
   4   NULL                  NULL
       ...                   ...
4172   NULL                  NULL
4173   NULL                  NULL
4174   NULL                  NULL
4175   NULL                  NULL
4176   NULL                  NULL


4177 rows x 10 columns
memory usage: 0.42 MB
type: getml.DataFrame

In [8]:
# TODO: Annotate columns with roles
invoices

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   5733            NULL            3               NULL            ...   NULL            NULL            NULL
   1   5734            NULL            2               NULL            ...   NULL            NULL            NULL
   2   5735            NULL            1               NULL            ...   NULL            NULL            NULL
   3   5736            NULL            1               NULL            ...   NULL            NULL            NULL
   4   5737            NULL            4               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
 933   8235            NULL            1               NULL            ...   NULL            NULL            NULL
 934   8236            NULL            1               NULL            ...   NULL            NULL            NULL
 935   8265            NULL            1               NULL            ...   NULL            NULL            NULL
 936   8371            NULL            3               NULL            ...   NULL            NULL            NULL
 937   8396            NULL            3               NULL            ...   NULL            NULL            NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   NULL                  NULL
   1   NULL                  NULL
   2   NULL                  NULL
   3   NULL                  NULL
   4   NULL                  NULL
       ...                   ...
 933   NULL                  NULL
 934   NULL                  NULL
 935   NULL                  NULL
 936   NULL                  NULL
 937   NULL                  NULL


938 rows x 10 columns
memory usage: 0.09 MB
type: getml.DataFrame

In [9]:
# TODO: Annotate columns with roles
craftsmen

name   number          number_sup      trip            trip_sup        ...   death_at_cape   left_at_cape    onboard_at_cape
role   unused_string   unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   1               NULL            1               NULL            ...   NULL            NULL            NULL
   1   2               NULL            1               NULL            ...   NULL            NULL            NULL
   2   3               NULL            1               NULL            ...   NULL            NULL            NULL
   3   4               NULL            1               NULL            ...   NULL            NULL            NULL
   4   5               NULL            1               NULL            ...   NULL            NULL            NULL
       ...             ...             ...             ...                   ...             ...             ...
2462   8392            NULL            1               NULL            ...   1               NULL            NULL
2463   8393            NULL            1               NULL            ...   1               1               NULL
2464   8394            NULL            1               NULL            ...   2               3               NULL
2465   8395            NULL            2               NULL            ...   NULL            3               NULL
2466   8398            NULL            2               NULL            ...   NULL            NULL            NULL

name   death_during_voyage   onboard_at_arrival
role   unused_string         unused_string
   0   NULL                  NULL
   1   NULL                  NULL
   2   NULL                  NULL
   3   NULL                  NULL
   4   NULL                  NULL
       ...                   ...
2462   NULL                  NULL
2463   NULL                  NULL
2464   NULL                  NULL
2465   NULL                  NULL
2466   NULL                  NULL


2467 rows x 10 columns
memory usage: 0.24 MB
type: getml.DataFrame

In [10]:
# TODO: Annotate columns with roles
passengers

name   number          number_sup      trip            trip_sup        invoice         chamber
role   unused_string   unused_string   unused_string   unused_string   unused_string   unused_string
   0   5102            NULL            2               NULL            268964          A
   1   5103            NULL            2               NULL            164562          Z
   2   5105            NULL            2               NULL            110370          A
   3   5106            NULL            2               NULL            127181          D
   4   5107            NULL            2               NULL            101522          A
       ...             ...             ...             ...             ...             ...
3777   8396            NULL            3               NULL            457491          A
3778   8397            NULL            1               NULL            365373          Z
3779   8399            NULL            1               NULL            50232           Z
3780   8400            NULL            1               NULL            85711           A
3781   8401            NULL            1               NULL            106435          A


3782 rows x 6 columns
memory usage: 0.25 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/voc](https://relational.fel.cvut.cz/dataset/voc)
for a description of the dataset.

In [11]:
dm = getml.data.DataModel(population=voyages.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [12]:
container = getml.data.Container(population=voyages, split=voyages.split)
container.add(**peripheral)

container

population
    subset   name      rows   type
0   train    voyages   5692   View
1   val      voyages   2439   View

peripheral
    name         rows   type
0   craftsmen    2349   DataFrame
1   passengers   2813   DataFrame
2   seafarers    4468   DataFrame
3   soldiers     4177   DataFrame
4   impotenten    938   DataFrame
5   total        2467   DataFrame
6   invoices     3782   DataFrame