In [1]:
import getml
from ctu.utils.data import load_ctu_dataset

getml.set_project("stats")

Connected to project 'stats'.

# Task: stats
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> The *stats* dataset is an anonymized collection of user-contributed content from the Stats Stack Exchange network. It is structured as a relational database with multiple interconnected tables, including `users`, `posts`, `comments`, `tags`, `postLinks`, `postHistory`, `votes`, and `badges`.
> 
> - **Data Model (Relational Schema):**
>   - **users**: Contains user information such as `Id`, `Reputation`, `CreationDate`, `DisplayName`, and other user-related attributes.
>   - **posts**: Includes details about posts like `Id`, `PostTypeId`, `Score`, `ViewCount`, `Body`, `Title`, and more.
>   - **comments**: Holds comment data with fields like `Id`, `PostId`, `Score`, `Text`, and `UserId`.
>   - **tags**: Contains tag information with `Id`, `TagName`, and `Count`.
>   - **postLinks**, **postHistory**, **votes**, **badges**: Additional tables providing links between posts, historical edits, voting data, and user badges.
> 
> - **Task and Target Column:**
>   - The primary task is *regression*, with the target column being `Reputation` in the `users` table. The goal is to predict the reputation score of users based on various features.
> 
> - **Column Types:**
>   - *Numeric*: `Reputation`, `Score`, `ViewCount`, `AnswerCount`, etc.
>   - *String*: `DisplayName`, `Title`, `Tags`, `Text`, etc.
>   - *Temporal*: `CreationDate`, `LastAccessDate`, `LastEditDate`, etc.
> 
> - **Metadata:**
>   - Size: 658.4 MB
>   - Number of Tables: 8
>   - Number of Rows: 1,027,838
>   - Number of Columns: 71
>   - Missing Values: Yes
>   - Compound Keys: No
>   - Loops: Yes
>   - Type: Real
>   - Instance Count: 41,793
> 
> The dataset has been used in various research papers and projects, particularly for tasks involving feature learning and prediction pipelines. Algorithms like FastProp, Relboost, and Deep Feature Synthesis have been applied to this dataset, achieving high R2 scores and low RMSE and MAE values, indicating effective prediction of user reputation.

### Tables
Population table: users

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/stats.svg" alt="stats ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [2]:
users, peripheral = load_ctu_dataset("stats")

(
    badges,
    comments,
    post_history,
    post_links,
    posts,
    tags,
    votes,
) = peripheral.values()

Analyzing schema:   0%|          | 0/8 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/8 [00:00<?, ?it/s]

Building data:   0%|          | 0/8 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`users`).

We already set the `target` role for the target (`Reputation`).


Reputation is the target column for a regression task.

In [3]:
# TODO: Annotate remaining columns with roles
users

 name   Reputation   Id              CreationDate                 DisplayName      ...   DownVotes       AccountId
 role       target   unused_string   unused_string                unused_string    ...   unused_string   unused_string
    0            1   -1              2010-07-19 06:55:26.000000   Community        ...   1920            -1
    1          101   2               2010-07-19 14:01:36.000000   Geoff Dalgas     ...   0               2
    2          101   3               2010-07-19 15:34:50.000000   Jarrod Dixon     ...   0               3
    3          101   4               2010-07-19 19:03:27.000000   Emmett           ...   0               1998
    4         6792   5               2010-07-19 19:03:57.000000   Shane            ...   5               54503
               ...   ...             ...                          ...                    ...             ...
40320            1   55743           2014-09-13 21:03:50.000000   AussieMeg        ...   0               5026902
40321            6   55744           2014-09-13 21:39:30.000000   Mia Maria        ...   0               5026998
40322          101   55745           2014-09-13 23:45:27.000000   tronbabylove     ...   0               481766
40323          106   55746           2014-09-14 00:29:41.000000   GPP              ...   0               976289
40324            1   55747           2014-09-14 01:01:44.000000   Shivam Agrawal   ...   0               5027354

 name   Age             ProfileImageUrl                    split
 role   unused_string   unused_string                      unused_string
    0   NULL            NULL                               train
    1   37              NULL                               train
    2   35              NULL                               train
    3   28              http://i.stack.imgur.com/d1oHX.j...   train
    4   35              NULL                               train
        ...             ...                                ...
40320   NULL            http://graph.facebook.com/665821...   train
40321   NULL            NULL                               train
40322   NULL            https://www.gravatar.com/avatar/...   train
40323   NULL            https://www.gravatar.com/avatar/...   train
40324   NULL            https://lh4.googleusercontent.co...   train


40325 rows x 15 columns
memory usage: 12.27 MB
type: getml.DataFrame

Peripheral tables,

In [4]:
# TODO: Annotate columns with roles
badges

 name   Id              UserId          Name             Date
 role   unused_string   unused_string   unused_string    unused_string
    0   1               5               Teacher          2010-07-19 19:39:07.000000
    1   2               6               Teacher          2010-07-19 19:39:07.000000
    2   3               8               Teacher          2010-07-19 19:39:07.000000
    3   4               23              Teacher          2010-07-19 19:39:07.000000
    4   5               36              Teacher          2010-07-19 19:39:07.000000
        ...             ...             ...              ...
79846   92236           55744           Student          2014-09-13 23:25:21.000000
79847   92237           1118            Nice Answer      2014-09-14 00:09:35.000000
79848   92238           1118            Enlightened      2014-09-14 01:18:29.000000
79849   92239           55746           Student          2014-09-14 01:41:18.000000
79850   92240           12597           Autobiographer   2014-09-14 02:31:28.000000


79851 rows x 4 columns
memory usage: 6.42 MB
type: getml.DataFrame

In [5]:
# TODO: Annotate columns with roles
comments

  name   Id              PostId          Score           Text                               CreationDate
  role   unused_string   unused_string   unused_string   unused_string                      unused_string
     0   1               3               5               Could be a poster child fo argum...   2010-07-19 19:15:52.000000
     1   2               5               0               Yes, R is nice- but WHY is it 'v...   2010-07-19 19:16:14.000000
     2   3               9               0               Again- why?  How would I convinc...   2010-07-19 19:18:54.000000
     3   4               5               11              It's mature, well supported, and...   2010-07-19 19:19:56.000000
     4   5               3               1               Define "valuable"...               2010-07-19 19:20:28.000000
         ...             ...             ...             ...                                ...
174300   221288          52312           0               You and Bogdanovist are in disag...   2014-09-14 01:45:11.000000
174301   221289          115376          0               @gung goal would be to say "Vide...   2014-09-14 01:45:19.000000
174302   221290          52312           0               Especially for small datasets wh...   2014-09-14 01:47:33.000000
174303   221291          115374          0               In fact, odds of 1-1 are said to...   2014-09-14 01:49:32.000000
174304   221292          115374          1               @DilipSarwate indeed, in that ca...   2014-09-14 02:04:27.000000

  name   UserId          UserDisplayName
  role   unused_string   unused_string
     0   13              NULL
     1   13              NULL
     2   13              NULL
     3   37              NULL
     4   5               NULL
         ...             ...
174300   13564           NULL
174301   55746           NULL
174302   13564           NULL
174303   6633            NULL
174304   805             NULL


174305 rows x 7 columns
memory usage: 58.27 MB
type: getml.DataFrame

In [6]:
# TODO: Annotate columns with roles
post_history

  name   Id              PostHistoryTypeId   PostId          RevisionGUID                       CreationDate
  role   unused_string   unused_string       unused_string   unused_string                      unused_string
     0   1               2                   1               e58bf7fd-e60f-4c58-a6e4-dfc91cf9...   2010-07-19 19:12:12.000000
     1   2               1                   1               e58bf7fd-e60f-4c58-a6e4-dfc91cf9...   2010-07-19 19:12:12.000000
     2   3               3                   1               e58bf7fd-e60f-4c58-a6e4-dfc91cf9...   2010-07-19 19:12:12.000000
     3   4               2                   2               18bf9150-f1cb-432d-b7b7-26d2f8e3...   2010-07-19 19:12:57.000000
     4   5               1                   2               18bf9150-f1cb-432d-b7b7-26d2f8e3...   2010-07-19 19:12:57.000000
         ...             ...                 ...             ...                                ...
303182   386844          5                   115374          a2993ae0-60b6-4d75-b25c-a0432cea...   2014-09-14 02:05:41.000000
303183   386845          2                   115378          cd2f9fc8-4866-438d-8d3d-773d269e...   2014-09-14 02:09:23.000000
303184   386846          5                   115377          165fb086-f35b-428a-bf63-2978beb5...   2014-09-14 02:46:55.000000
303185   386847          25                  115376          1f889b64-5963-4539-ab57-dc6a8457...   2014-09-14 02:52:43.000000
303186   386848          5                   115377          91050683-844a-4e89-ad8e-f00f564b...   2014-09-14 02:54:13.000000

  name   UserId          Text                               Comment                            UserDisplayName
  role   unused_string   unused_string                      unused_string                      unused_string
     0   8               How should I elicit prior distri...   NULL                               NULL
     1   8               Eliciting priors from experts      NULL                               NULL
     2   8               <bayesian><prior><elicitation>     NULL                               NULL
     3   24              In many different statistical me...   NULL                               NULL
     4   24              What is normality?                 NULL                               NULL
         ...             ...                                ...                                ...
303182   805             This grew too long for a comment...   added 1 character in body          NULL
303183   7250            Decision trees are notoriously *...   NULL                               NULL
303184   805             As a practical answer to the rea...   added 494 characters in body       NULL
303185   NULL            NULL                               http://twitter.com/#!/StackStats...   NULL
303186   805             As a practical answer to the rea...   added 92 characters in body        NULL


303187 rows x 9 columns
memory usage: 251.29 MB
type: getml.DataFrame

In [7]:
# TODO: Annotate columns with roles
post_links

 name   Id              CreationDate                 PostId          RelatedPostId   LinkTypeId
 role   unused_string   unused_string                unused_string   unused_string   unused_string
    0   108             2010-07-21 14:47:33.000000   395             173             1
    1   145             2010-07-23 16:30:41.000000   548             539             1
    2   217             2010-07-26 20:12:15.000000   375             30              1
    3   263             2010-07-27 16:00:22.000000   769             31              1
    4   264             2010-07-27 16:00:22.000000   769             6               1
        ...             ...                          ...             ...             ...
11097   3356577         2014-09-13 09:51:24.000000   104882          104565          1
11098   3356634         2014-09-13 14:24:45.000000   115343          51061           1
11099   3356635         2014-09-13 15:07:09.000000   115304          5135            3
11100   3356755         2014-09-13 18:43:55.000000   115327          31326           3
11101   3356789         2014-09-13 20:54:31.000000   115360          60438           1


11102 rows x 5 columns
memory usage: 0.98 MB
type: getml.DataFrame

In [8]:
# TODO: Annotate columns with roles
posts

 name   Id              PostTypeId      AcceptedAnswerId   CreaionDate                  ...   CommunityOwnedDate
 role   unused_string   unused_string   unused_string      unused_string                ...   unused_string
    0   1               1               15                 2010-07-19 19:12:12.000000   ...   NULL
    1   2               1               59                 2010-07-19 19:12:57.000000   ...   NULL
    2   3               1               5                  2010-07-19 19:13:28.000000   ...   2010-07-19 19:13:28.000000
    3   4               1               135                2010-07-19 19:13:31.000000   ...   NULL
    4   5               2               NULL               2010-07-19 19:14:43.000000   ...   2010-07-19 19:14:43.000000
        ...             ...             ...                ...                                ...
91971   115374          2               NULL               2014-09-13 23:45:39.000000   ...   NULL
91972   115375          1               NULL               2014-09-13 23:46:05.000000   ...   NULL
91973   115376          1               NULL               2014-09-14 01:27:54.000000   ...   NULL
91974   115377          2               NULL               2014-09-14 02:03:28.000000   ...   NULL
91975   115378          2               NULL               2014-09-14 02:09:23.000000   ...   NULL

 name   ParentId        ClosedDate      OwnerDisplayName   LastEditorDisplayName
 role   unused_string   unused_string   unused_string      unused_string
    0   NULL            NULL            NULL               NULL
    1   NULL            NULL            NULL               NULL
    2   NULL            NULL            NULL               NULL
    3   NULL            NULL            NULL               NULL
    4   3               NULL            NULL               NULL
        ...             ...             ...                ...
91971   115367          NULL            NULL               NULL
91972   NULL            NULL            NULL               NULL
91973   NULL            NULL            NULL               NULL
91974   115358          NULL            NULL               NULL
91975   115375          NULL            NULL               NULL


91976 rows x 21 columns
memory usage: 132.85 MB
type: getml.DataFrame

In [9]:
# TODO: Annotate columns with roles
tags

name   Id              TagName                   Count           ExcerptPostId   WikiPostId
role   unused_string   unused_string             unused_string   unused_string   unused_string
   0   1               bayesian                  1342            20258           20257
   1   2               prior                     168             62158           62157
   2   3               elicitation               6               NULL            NULL
   3   4               normality                 191             67815           67814
   4   5               open-source               13              NULL            NULL
       ...             ...                       ...             ...             ...
1027   1865            roxygen2                  1               NULL            NULL
1028   1866            package-development       1               NULL            NULL
1029   1867            generilzed-linear-model   1               NULL            NULL
1030   1868            standard                  1               NULL            NULL
1031   1869            zero-inflated             1               NULL            NULL


1032 rows x 5 columns
memory usage: 0.07 MB
type: getml.DataFrame

In [10]:
# TODO: Annotate columns with roles
votes

  name   Id              PostId          VoteTypeId      CreationDate    UserId          BountyAmount
  role   unused_string   unused_string   unused_string   unused_string   unused_string   unused_string
     0   1               3               2               2010-07-19      NULL            NULL
     1   2               2               2               2010-07-19      NULL            NULL
     2   3               5               2               2010-07-19      NULL            NULL
     3   4               5               2               2010-07-19      NULL            NULL
     4   5               3               2               2010-07-19      NULL            NULL
         ...             ...             ...             ...             ...             ...
328059   386254          26088           2               2014-09-14      NULL            NULL
328060   386255          26088           5               2014-09-14      31466           NULL
328061   386256          115374          2               2014-09-14      NULL            NULL
328062   386257          115368          2               2014-09-14      NULL            NULL
328063   386258          115369          2               2014-09-14      NULL            NULL


328064 rows x 6 columns
memory usage: 24.93 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/stats](https://relational.fel.cvut.cz/dataset/stats)
for a description of the dataset.

In [11]:
dm = getml.data.DataModel(population=users.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

# TODO
# dm.population.join(...)

Now we can create the container and add the tables to it.

In [12]:
container = getml.data.Container(population=users, split=users.split)
container.add(**peripheral)

container

population
    subset   name     rows   type
0   train    users   28228   View
1   val      users   12097   View

peripheral
    alias          name            rows   type
0   badges         badges         79851   DataFrame
1   comments       comments      174305   DataFrame
2   post_history   postHistory   303187   DataFrame
3   post_links     postLinks      11102   DataFrame
4   posts          posts          91976   DataFrame
5   tags           tags            1032   DataFrame
6   votes          votes         328064   DataFrame